//! A profile-private store for a short-lived secret that must be handed to a **human**.
//!
//! # Why this exists at all
//!
//! An approval's one-time decision nonce is generated by the platform, stored durably as a SHA-256
//! **digest** (`ADR-0018`), and has to be **presented** to decide the approval: `record_decision`
//! compares the presented value against that digest. So the plaintext must live somewhere between the
//! request being held and the decision being made, and there were only three places it could go:
//!
//! 1. **Only in the daemon's memory.** A restart loses it, and an approval that survives a restart is
//!    precisely what `A05`/the Phase 3 gate require. Rejected.
//! 2. **In the response that requested the approval.** That response is produced on the path a
//!    tool-call request travels, and the requester of a tool call is the **run** — the agent. The nonce
//!    exists to defeat *model self-approval* (`docs/architecture/security.md`), so handing it to the
//!    requester would be a control that hands the key to the party it excludes. Rejected.
//! 3. **In a file only the human's own account can read.** This module.
//!
//! `ADR-0018` also rejected deriving the nonce from a server secret, for a reason worth restating
//! because it rules out the tempting fourth option: a derived value "stays valid until the secret
//! rotates", so it is not one-time and a leaked derivation is a permanent ability to approve.
//!
//! # The shape, and the precedent it follows
//!
//! This is the same shape the daemon already uses for its own client credential
//! ([`crate::CredentialStore`]): the daemon **issues** a secret into a file the human's account can read,
//! and the secret is never carried in a request body and never returned to whoever asked for the action.
//! A tool call cannot name its own approver and cannot read this file through the tool pipeline; the
//! operator's own client reads it, exactly as it reads the profile credential.
//!
//! # The one-time property belongs to the digest; the file is delivery and defence in depth
//!
//! `record_decision` compares a **presented** nonce against the stored digest and rotates that digest to
//! the digest of the empty string once the guarded write lands (`ADR-0018`). Nothing can match the rotated
//! digest again, in any process or across any restart, whether or not a file survives. **That rotation is
//! the control.**
//!
//! [`SecretStore`] removes the delivered file as well, which is deliberate layering: it keeps a
//! presentable secret from sitting on disk for the remainder of an approval's lifetime, and it makes the
//! delivery single-read for the operator's client ([`SecretStore::take`]). Both failure directions stay
//! safe — a lost file makes an approval **undecidable** (recoverable by requesting the action again)
//! rather than **reusable**, and a file that outlives a decision is inert because its digest has rotated.
//!
//! **The daemon does not read the nonce from this file when a decision arrives.** The file is a delivery
//! channel and the operator's own client is its legitimate reader; a daemon that consumed it first would
//! refuse a decision the operator had every right to make, and the route's answer would rest on
//! filesystem state rather than on the caller's credential. The daemon verifies what is **presented** and
//! discards the file afterwards.

use std::fs;
use std::io::{self, Write};
use std::path::{Path, PathBuf};
use std::str::FromStr;

use atomic_write_file::AtomicWriteFile;
use jarvis_core::{ApprovalId, DecisionNonce};

use crate::paths::{PathKind, secure_private_file};

/// Directory, beneath the profile's state directory, holding pending decision nonces.
pub const APPROVAL_NONCE_DIRECTORY: &str = "approvals";

/// Explains why a pending decision nonce could not be stored or taken.
#[derive(Debug, thiserror::Error)]
pub enum SecretStoreError {
    /// The identifier cannot name a file in this store.
    ///
    /// The identifier is parsed as an `ApprovalId` before it is ever joined to a path, so a traversal
    /// or an absolute path is refused as a malformed identifier rather than reaching the filesystem.
    #[error("`{approval_id}` is not an approval identifier this store can name a file for")]
    InvalidId {
        /// The identifier that was refused.
        approval_id: String,
    },
    /// No nonce is held for that approval.
    ///
    /// The ordinary causes are a daemon restart (the file was on a temporary filesystem), a decision
    /// that already consumed it, or an approval created by a build that did not write one. All three
    /// are reported the same way because the caller's action is the same in every case: the approval
    /// cannot be decided and must be requested again.
    #[error("no decision nonce is held for approval {approval_id}")]
    Absent {
        /// The approval that was looked up.
        approval_id: String,
    },
    /// The stored text is not a decision nonce.
    #[error("the stored decision nonce for {approval_id} is not a valid nonce")]
    Invalid {
        /// The approval whose stored value was unreadable.
        approval_id: String,
    },
    /// The store could not be read or written.
    #[error("the decision nonce store could not be used")]
    Io {
        /// The underlying operating-system error.
        #[source]
        source: io::Error,
    },
    /// The stored file is not private to the current user.
    #[error("the decision nonce file is not private to the current user")]
    Insecure {
        /// The underlying cause, from the path utilities.
        #[source]
        source: crate::paths::PathError,
    },
}

/// Stores one pending decision nonce per approval, in a profile-private directory.
#[derive(Clone, Debug)]
pub struct SecretStore {
    directory: PathBuf,
}

impl SecretStore {
    /// Creates a store rooted at an explicit directory.
    #[must_use]
    pub fn at(directory: impl Into<PathBuf>) -> Self {
        Self {
            directory: directory.into(),
        }
    }

    /// Creates a store beneath a profile's state directory.
    ///
    /// State rather than cache or runtime, deliberately. A cache may be cleared by the OS at any time,
    /// and a runtime directory is login-lifetime on Linux — either would silently make every pending
    /// approval undecidable across a logout or a reboot, which is the restart case `A05` tests. State is
    /// the directory the profile's own durable data lives in.
    #[must_use]
    pub fn in_state(state: &Path) -> Self {
        Self::at(state.join(APPROVAL_NONCE_DIRECTORY))
    }

    /// Returns the directory nonces are stored in.
    #[must_use]
    pub fn directory(&self) -> &Path {
        &self.directory
    }

    /// Returns the file a given approval's nonce is stored in.
    ///
    /// # Errors
    ///
    /// Returns [`SecretStoreError::InvalidId`] when the identifier is not a well-formed `ApprovalId`.
    /// Parsing rather than sanitizing is the point: the identifier is joined to a path below, so a value
    /// like `../../etc/passwd` has to be **unrepresentable** rather than escaped.
    pub fn path_for(&self, approval_id: &str) -> Result<PathBuf, SecretStoreError> {
        let id = ApprovalId::from_str(approval_id).map_err(|_| SecretStoreError::InvalidId {
            approval_id: approval_id.to_owned(),
        })?;
        Ok(self.directory.join(id.to_string()))
    }

    /// Writes a pending nonce for an approval.
    ///
    /// A repeat write for the same approval **replaces** the value rather than failing: the store's
    /// subject is "the nonce currently pending for this approval", and a hold that re-runs for an
    /// adopted call has no way to know a previous one was written. What must not happen is a second
    /// approval being able to decide against the first's intent, and that is prevented by the intent
    /// check on the decision path rather than here.
    ///
    /// # Errors
    ///
    /// Returns [`SecretStoreError::InvalidId`] for an unusable identifier, [`SecretStoreError::Io`]
    /// when the directory or file cannot be written, and [`SecretStoreError::Insecure`] when the file
    /// cannot be restricted to the current user.
    pub fn store(&self, approval_id: &str, nonce: &DecisionNonce) -> Result<(), SecretStoreError> {
        let path = self.path_for(approval_id)?;
        fs::create_dir_all(&self.directory).map_err(|source| SecretStoreError::Io { source })?;

        let mut file =
            AtomicWriteFile::open(&path).map_err(|source| SecretStoreError::Io { source })?;
        file.write_all(nonce.expose().as_bytes())
            .map_err(|source| SecretStoreError::Io { source })?;
        file.commit()
            .map_err(|source| SecretStoreError::Io { source })?;

        // Refuses a symlink as well as enforcing user-only access, which matters because this file is
        // the one place a secret is written to a path derived from a caller-supplied identifier.
        secure_private_file(PathKind::State, &path)
            .map_err(|source| SecretStoreError::Insecure { source })
    }

    /// Takes the pending nonce for an approval, consuming it.
    ///
    /// # The removal happens BEFORE the value is returned
    ///
    /// A value returned before its file is removed could be handed out twice if the process died in
    /// between, and removing first makes the crash direction the safe one: the approval becomes
    /// **undecidable** — recoverable by requesting the action again — rather than **reusable**. It also
    /// makes the delivery single-read: two concurrent callers race on one `remove_file` and exactly one
    /// observes the value.
    ///
    /// # This is the *client's* read, not the daemon's
    ///
    /// The operator's own client reads the delivered nonce this way. The daemon **must not**: the route
    /// that records a decision verifies the nonce the caller **presents** and then discards the file, so
    /// that a client which has legitimately read the delivery is not defeated by the daemon having
    /// consumed it first. See the module header.
    ///
    /// # Errors
    ///
    /// Returns [`SecretStoreError::Absent`] when nothing is held (including the case where another
    /// caller won the race), [`SecretStoreError::InvalidId`] for an unusable identifier, and
    /// [`SecretStoreError::Invalid`] when the stored text is not a nonce.
    pub fn take(&self, approval_id: &str) -> Result<DecisionNonce, SecretStoreError> {
        let path = self.path_for(approval_id)?;

        let text = match fs::read_to_string(&path) {
            Ok(text) => text,
            Err(source) if source.kind() == io::ErrorKind::NotFound => {
                return Err(SecretStoreError::Absent {
                    approval_id: approval_id.to_owned(),
                });
            }
            Err(source) => return Err(SecretStoreError::Io { source }),
        };

        // Consumed regardless of whether the text parses: a stored value that is not a nonce is not a
        // nonce that should get a second chance, and leaving it would let a retry loop repeat the read.
        match fs::remove_file(&path) {
            Ok(()) => {}
            Err(source) if source.kind() == io::ErrorKind::NotFound => {
                return Err(SecretStoreError::Absent {
                    approval_id: approval_id.to_owned(),
                });
            }
            Err(source) => return Err(SecretStoreError::Io { source }),
        }

        DecisionNonce::parse(&text).map_err(|_| SecretStoreError::Invalid {
            approval_id: approval_id.to_owned(),
        })
    }

    /// Removes any pending nonce for an approval, reporting whether one was present.
    ///
    /// Used when a decision has already been recorded, so a decided approval does not leave a presentable
    /// secret on disk for the remainder of its lifetime.
    ///
    /// # Errors
    ///
    /// Returns [`SecretStoreError::InvalidId`] for an unusable identifier and [`SecretStoreError::Io`]
    /// for any failure other than absence.
    pub fn discard(&self, approval_id: &str) -> Result<bool, SecretStoreError> {
        let path = self.path_for(approval_id)?;
        match fs::remove_file(&path) {
            Ok(()) => Ok(true),
            Err(source) if source.kind() == io::ErrorKind::NotFound => Ok(false),
            Err(source) => Err(SecretStoreError::Io { source }),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    struct TestDirectory(PathBuf);

    impl TestDirectory {
        fn new() -> Self {
            let path = std::env::temp_dir().join(format!(
                "jarvis-storage-secrets-{}",
                jarvis_core::scratch_tag()
            ));
            fs::create_dir_all(&path).unwrap_or_else(|error| panic!("create temp dir: {error}"));
            Self(path)
        }
    }

    impl Drop for TestDirectory {
        fn drop(&mut self) {
            jarvis_core::remove_scratch_dir(&self.0);
        }
    }

    fn approval() -> String {
        ApprovalId::new().to_string()
    }

    fn must<T, E: std::fmt::Debug>(result: Result<T, E>) -> T {
        match result {
            Ok(value) => value,
            Err(error) => panic!("expected success, got {error:?}"),
        }
    }

    #[test]
    fn a_stored_nonce_can_be_taken_once() {
        let directory = TestDirectory::new();
        let store = SecretStore::at(directory.0.join(APPROVAL_NONCE_DIRECTORY));
        let id = approval();
        let nonce = must(DecisionNonce::generate());

        must(store.store(&id, &nonce));
        let taken = must(store.take(&id));
        assert_eq!(taken, nonce, "the taken nonce must be the stored one");

        // **The one-time property.** A second take finds nothing, because the first removed the file.
        // Asserted on the *variant* rather than on `is_err`, so a permission error or a corrupt file
        // cannot make this pass for the wrong reason.
        let second = store.take(&id);
        assert!(
            matches!(second, Err(SecretStoreError::Absent { .. })),
            "a nonce must not be presentable twice, got {second:?}"
        );
    }

    #[test]
    fn taking_an_approval_with_no_stored_nonce_reports_absence() {
        let directory = TestDirectory::new();
        let store = SecretStore::at(directory.0.join(APPROVAL_NONCE_DIRECTORY));
        let result = store.take(&approval());
        assert!(
            matches!(result, Err(SecretStoreError::Absent { .. })),
            "a restart or a consumed nonce is an absence, not a fault, got {result:?}"
        );
    }

    /// **The identifier is parsed, so a traversal cannot name a path.**
    ///
    /// The point is that the value is not merely rejected — it is rejected *before* reaching the
    /// filesystem, so there is no escaping scheme to get wrong.
    #[test]
    fn an_identifier_that_is_not_an_approval_cannot_name_a_file() {
        let directory = TestDirectory::new();
        let store = SecretStore::at(directory.0.join(APPROVAL_NONCE_DIRECTORY));
        for hostile in [
            "../../escape",
            "..",
            "/absolute",
            "C:\\absolute",
            "not-a-uuid",
            "",
        ] {
            let result = store.path_for(hostile);
            assert!(
                matches!(result, Err(SecretStoreError::InvalidId { .. })),
                "`{hostile}` must not name a file, got {result:?}"
            );
        }
    }

    #[test]
    fn a_discard_reports_whether_anything_was_there() {
        let directory = TestDirectory::new();
        let store = SecretStore::at(directory.0.join(APPROVAL_NONCE_DIRECTORY));
        let id = approval();
        must(store.store(&id, &must(DecisionNonce::generate())));

        assert!(
            must(store.discard(&id)),
            "the stored nonce must be reported as present"
        );
        assert!(
            !must(store.discard(&id)),
            "a second discard must report absence"
        );
        assert!(
            matches!(store.take(&id), Err(SecretStoreError::Absent { .. })),
            "a discarded nonce must not be takeable"
        );
    }

    /// A stored value that is not a nonce is consumed and reported, never returned.
    #[test]
    fn a_corrupt_stored_value_is_reported_as_invalid_and_not_reused() {
        let directory = TestDirectory::new();
        let store = SecretStore::at(directory.0.join(APPROVAL_NONCE_DIRECTORY));
        let id = approval();
        let path = must(store.path_for(&id));
        fs::create_dir_all(directory.0.join(APPROVAL_NONCE_DIRECTORY))
            .unwrap_or_else(|error| panic!("mkdir: {error}"));
        fs::write(&path, "not-a-nonce").unwrap_or_else(|error| panic!("write: {error}"));

        let result = store.take(&id);
        assert!(
            matches!(result, Err(SecretStoreError::Invalid { .. })),
            "a corrupt value must be reported as invalid, got {result:?}"
        );
        assert!(!path.exists(), "a corrupt value must still be consumed");
    }
}
