//! Durable approval requests: a decision record, never a bearer token.
//!
//! `docs/architecture/security.md` describes an approval as "a decision record, not a model message",
//! and `docs/architecture/events-and-workflows.md` adds the constraint that decides the whole design:
//! "Approval is not a permanent bearer token."
//!
//! # Four things this module makes unrepresentable
//!
//! 1. **An approval without a bound intent.** [`CanonicalIntentHash`] is computed from the tool, its
//!    version, and the exact arguments. `security.md`: "Editing the action invalidates the approval."
//!    A hash that a caller could supply would be a hash a caller could supply wrongly, so the
//!    constructor computes it from the parts rather than accepting one.
//! 2. **A nonce that is not a secret.** [`DecisionNonce`] is 32 random bytes generated by the
//!    platform, compared in constant time, and redacted from `Debug`. `security.md` lists "model
//!    self-approval / confused deputy" as a threat whose control is an "authenticated approval
//!    receipt"; a nonce a model could read or guess would be neither.
//! 3. **An approval weaker than the action.** The required [`AuthenticationStrength`] is a field of
//!    the request, and a decision below it is refused by [`ApprovalRequest::apply_decision`] rather
//!    than recorded.
//! 4. **An approval that outlives its intent.** Expiry is checked by [`ApprovalRequest::state_at`],
//!    and the state is derived from the stored decision plus the clock — so a lapsed approval cannot
//!    report itself approved, whatever a caller asks.
//!
//! # Why expiry is compared in Rust and not in SQL
//!
//! `crates/jarvis-core/tests` pins a real defect: [`crate::UtcTimestamp`]'s stored form omits the
//! fractional part when it is zero, so `"...00Z"` sorts **after** `"...00.5Z"` as text. A SQL
//! predicate like `expires_at < now` would therefore treat an expired row as unexpired. Expiry here
//! is compared with [`UtcTimestamp::unix_nanos`], which is the same instant and always comparable.

use std::fmt;
use std::str::FromStr;

use serde::{Deserialize, Serialize};
use thiserror::Error;

use crate::credential::{CREDENTIAL_BYTES, CREDENTIAL_CHARS};
use crate::error::SafeMessage;
use crate::id::{ApprovalId, CorrelationId, RunId, WorkspaceId};
use crate::secretbytes::{constant_time_eq, encode_hex};
use crate::timestamp::{Clock, UtcTimestamp};

/// Maximum characters in a human-readable approval preview.
///
/// Bounded because the preview reaches a person on an approval prompt and a client on every channel.
/// It is a *preview*: the canonical intent hash is what the decision binds to, so shortening the
/// preview cannot change what was approved.
pub const MAX_APPROVAL_PREVIEW_CHARS: usize = 512;

/// Maximum characters in a canonicalized intent string.
///
/// Bounded before hashing, so an enormous argument object cannot make the hash computation itself a
/// denial-of-service, and so the limit is the same for the value that is stored and hashed.
pub const MAX_CANONICAL_INTENT_CHARS: usize = 8192;

/// Maximum approval lifetime in seconds.
///
/// Bounded because an approval that outlives its intent is the failure mode the expiry exists to
/// prevent, and `docs/architecture/events-and-workflows.md` requires an expiry on every approval. An
/// hour is long enough for a person to answer a prompt and short enough that a stored grant cannot
/// survive an incident response.
pub const MAX_APPROVAL_LIFETIME_SECONDS: u32 = 3600;

/// Explains why a canonical intent could not be hashed.
#[derive(Clone, Copy, Debug, Eq, Error, PartialEq)]
pub enum IntentError {
    /// The canonicalized text was empty.
    #[error("a canonical intent must not be empty")]
    Empty,
    /// The canonicalized text exceeded the bound.
    #[error("a canonical intent exceeds {MAX_CANONICAL_INTENT_CHARS} characters")]
    TooLong,
    /// The arguments were not a JSON object.
    ///
    /// A tool's input schema is an object, so arguments that are not an object did not come from a
    /// validated call and cannot be canonicalized deterministically.
    #[error("tool arguments must be a JSON object")]
    ArgumentsNotAnObject,
    /// The arguments could not be canonicalized.
    #[error("tool arguments could not be canonicalized")]
    NotCanonicalizable,
}

/// A digest of exactly the intent a decision approves.
///
/// The value is a lowercase hexadecimal SHA-256 digest. It is stored and compared, so the
/// representation is the digest itself rather than a wrapper enum that could hold a value it did not
/// compute.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub struct CanonicalIntentHash([u8; 32]);

impl CanonicalIntentHash {
    /// Computes the hash of a tool call's intent.
    ///
    /// # Errors
    ///
    /// Returns [`IntentError::ArgumentsNotAnObject`] when `arguments` is not an object,
    /// [`IntentError::NotCanonicalizable`] when it cannot be serialized,
    /// [`IntentError::Empty`] when no part is usable, and [`IntentError::TooLong`] when the
    /// canonicalized text exceeds [`MAX_CANONICAL_INTENT_CHARS`].
    ///
    /// # Why the parts are hashed with separators
    ///
    /// The canonical text joins tool, version, and canonicalized arguments with a character that
    /// cannot appear in an identifier (`\u{1f}`). Without a separator, a tool named `a` with version
    /// `bc` and a tool named `ab` with version `c` would produce the same digest, so one approval
    /// would authorize the other.
    pub fn compute(
        tool: &str,
        tool_version: &str,
        arguments: &serde_json::Value,
    ) -> Result<Self, IntentError> {
        use sha2::{Digest, Sha256};

        if !arguments.is_object() {
            return Err(IntentError::ArgumentsNotAnObject);
        }
        let canonical_arguments = canonicalize(arguments)?;
        let canonical = format!("{tool}\u{1f}{tool_version}\u{1f}{canonical_arguments}");
        if canonical.trim().is_empty() {
            return Err(IntentError::Empty);
        }
        if canonical.chars().count() > MAX_CANONICAL_INTENT_CHARS {
            return Err(IntentError::TooLong);
        }

        let mut hasher = Sha256::new();
        hasher.update(canonical.as_bytes());
        let digest = hasher.finalize();
        let mut bytes = [0u8; 32];
        bytes.copy_from_slice(&digest);
        Ok(Self(bytes))
    }

    /// Returns the digest as lowercase hexadecimal.
    #[must_use]
    pub fn to_hex(self) -> String {
        encode_hex(&self.0)
    }
}

impl fmt::Display for CanonicalIntentHash {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(&self.to_hex())
    }
}

impl FromStr for CanonicalIntentHash {
    type Err = IntentError;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        // A digest is 32 bytes, so the hex text is exactly 64 characters. Anything else did not
        // come from `compute`, so it is refused rather than padded or truncated.
        if value.len() != 64 || !value.bytes().all(|byte| byte.is_ascii_hexdigit()) {
            return Err(IntentError::NotCanonicalizable);
        }
        let mut bytes = [0u8; 32];
        for (index, chunk) in value.as_bytes().as_chunks::<2>().0.iter().enumerate() {
            let text = std::str::from_utf8(chunk).map_err(|_| IntentError::NotCanonicalizable)?;
            bytes[index] =
                u8::from_str_radix(text, 16).map_err(|_| IntentError::NotCanonicalizable)?;
        }
        Ok(Self(bytes))
    }
}

impl Serialize for CanonicalIntentHash {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        serializer.serialize_str(&self.to_hex())
    }
}

impl<'de> Deserialize<'de> for CanonicalIntentHash {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = String::deserialize(deserializer)?;
        value.parse().map_err(serde::de::Error::custom)
    }
}

/// Renders JSON with object keys in a deterministic order.
///
/// `serde_json::Map` is a `BTreeMap` unless the `preserve_order` feature is enabled, so its default
/// serialization is already sorted — but that is a property of a feature flag rather than of this
/// code, and a feature added for an unrelated reason would silently make two equal argument objects
/// hash differently. Sorting explicitly here makes the canonical form independent of that choice.
fn canonicalize(value: &serde_json::Value) -> Result<String, IntentError> {
    /// Rebuilds a value with object keys in ascending order.
    fn sorted(value: &serde_json::Value) -> serde_json::Value {
        match value {
            serde_json::Value::Object(object) => {
                let mut ordered = serde_json::Map::new();
                let mut keys: Vec<&String> = object.keys().collect();
                keys.sort();
                for key in keys {
                    if let Some(entry) = object.get(key) {
                        ordered.insert(key.clone(), sorted(entry));
                    }
                }
                serde_json::Value::Object(ordered)
            }
            serde_json::Value::Array(items) => {
                serde_json::Value::Array(items.iter().map(sorted).collect())
            }
            other => other.clone(),
        }
    }
    serde_json::to_string(&sorted(value)).map_err(|_| IntentError::NotCanonicalizable)
}

/// Explains why a decision nonce was rejected.
#[derive(Clone, Copy, Debug, Eq, Error, PartialEq)]
pub enum NonceError {
    /// The text was not the fixed encoded length.
    #[error("a decision nonce must be exactly {CREDENTIAL_CHARS} hexadecimal characters")]
    Length,
    /// The text contained a non-hexadecimal character.
    #[error("a decision nonce contains a non-hexadecimal character")]
    NotHexadecimal,
    /// The platform random source was unavailable.
    #[error("random bytes are unavailable")]
    RandomUnavailable,
}

/// The one-time secret an approval decision must present.
///
/// Generated by the platform, never by the model. `docs/architecture/security.md` lists a one-time
/// decision nonce as part of the record whose purpose is to defeat "model self-approval / confused
/// deputy", so a nonce the requesting model could read or choose would defeat the control it exists
/// for.
///
/// The value is zeroized on drop and redacted from `Debug`, because a nonce that reaches a log line
/// is a nonce that has leaked.
#[derive(Clone, Eq)]
pub struct DecisionNonce {
    encoded: Vec<u8>,
}

impl DecisionNonce {
    /// Generates a nonce from the platform random source.
    ///
    /// # Errors
    ///
    /// Returns [`NonceError::RandomUnavailable`] when the platform source fails. The failure is
    /// propagated rather than retried or replaced with a weaker source: an approval whose nonce was
    /// guessable is worse than an approval that could not be created.
    pub fn generate() -> Result<Self, NonceError> {
        let mut bytes = [0u8; CREDENTIAL_BYTES];
        getrandom::fill(&mut bytes).map_err(|_| NonceError::RandomUnavailable)?;
        Ok(Self {
            encoded: encode_hex(&bytes).into_bytes(),
        })
    }

    /// Parses a nonce from hexadecimal text, normalizing case and trimming.
    ///
    /// # Errors
    ///
    /// Returns [`NonceError::Length`] when the text is not the fixed encoded length, or
    /// [`NonceError::NotHexadecimal`] when it contains a non-hexadecimal character.
    pub fn parse(text: &str) -> Result<Self, NonceError> {
        let trimmed = text.trim();
        if trimmed.len() != CREDENTIAL_CHARS {
            return Err(NonceError::Length);
        }
        if !trimmed.bytes().all(|byte| byte.is_ascii_hexdigit()) {
            return Err(NonceError::NotHexadecimal);
        }
        Ok(Self {
            encoded: trimmed.to_ascii_lowercase().into_bytes(),
        })
    }

    /// Returns the encoded nonce for storage.
    ///
    /// Named `expose` to make each call a deliberate act, matching how the client credential is read.
    #[must_use]
    pub fn expose(&self) -> &str {
        // The buffer only ever holds validated ASCII hexadecimal bytes.
        str::from_utf8(&self.encoded).unwrap_or_default()
    }

    /// Compares a presented nonce in constant time.
    #[must_use]
    pub fn matches(&self, presented: &str) -> bool {
        constant_time_eq(&self.encoded, presented.as_bytes())
    }
}

impl PartialEq for DecisionNonce {
    /// Compares in constant time, so equality does not leak a prefix.
    fn eq(&self, other: &Self) -> bool {
        constant_time_eq(&self.encoded, &other.encoded)
    }
}

impl fmt::Debug for DecisionNonce {
    /// Redacts the value, so a nonce cannot reach a log or a panic message.
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str("DecisionNonce([REDACTED])")
    }
}

impl fmt::Display for DecisionNonce {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str("approval decision nonce [REDACTED]")
    }
}

impl Drop for DecisionNonce {
    fn drop(&mut self) {
        self.encoded.fill(0);
    }
}

/// How strong the authentication behind a decision was.
///
/// Deliberately distinct from `jarvis-tools`'s channel ceiling. The ceiling is what a channel *can*
/// establish; this is what the channel that answered *did* establish. Sharing one type would let a
/// caller record a ceiling as if it were an observation.
#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, Ord, PartialEq, PartialOrd, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum AuthenticationStrength {
    /// No authentication evidence.
    Absent,
    /// Channel evidence only, such as a caller ID.
    ChannelEvidence,
    /// A verified credential, such as a device credential.
    Credential,
    /// A credential established in this interaction, with user presence.
    Present,
}

impl AuthenticationStrength {
    /// Returns the stable wire and storage name.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Absent => "absent",
            Self::ChannelEvidence => "channel_evidence",
            Self::Credential => "credential",
            Self::Present => "present",
        }
    }

    /// Returns the numeric level, for comparison against a stored value.
    #[must_use]
    pub const fn level(self) -> u8 {
        match self {
            Self::Absent => 0,
            Self::ChannelEvidence => 1,
            Self::Credential => 2,
            Self::Present => 3,
        }
    }

    /// Returns every strength, from weakest to strongest.
    #[must_use]
    pub const fn all() -> [Self; 4] {
        [
            Self::Absent,
            Self::ChannelEvidence,
            Self::Credential,
            Self::Present,
        ]
    }
}

impl fmt::Display for AuthenticationStrength {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

impl FromStr for AuthenticationStrength {
    type Err = InvalidApprovalField;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "absent" => Ok(Self::Absent),
            "channel_evidence" => Ok(Self::ChannelEvidence),
            "credential" => Ok(Self::Credential),
            "present" => Ok(Self::Present),
            _ => Err(InvalidApprovalField::UnknownStrength),
        }
    }
}

/// Which channel answered.
///
/// Closed, and stored. A free-form channel name would be a place for content to enter an audit
/// record, which is the same reason the run event kinds are closed.
#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum ApprovalChannel {
    /// A terminal client.
    Cli,
    /// The desktop or web view.
    Desktop,
    /// An HTTP or IPC API client.
    Api,
    /// A voice or telephony session.
    Voice,
}

impl ApprovalChannel {
    /// Returns the stable wire and storage name.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Cli => "cli",
            Self::Desktop => "desktop",
            Self::Api => "api",
            Self::Voice => "voice",
        }
    }

    /// Returns every channel.
    #[must_use]
    pub const fn all() -> [Self; 4] {
        [Self::Cli, Self::Desktop, Self::Api, Self::Voice]
    }
}

impl fmt::Display for ApprovalChannel {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

impl FromStr for ApprovalChannel {
    type Err = InvalidApprovalField;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "cli" => Ok(Self::Cli),
            "desktop" => Ok(Self::Desktop),
            "api" => Ok(Self::Api),
            "voice" => Ok(Self::Voice),
            _ => Err(InvalidApprovalField::UnknownChannel),
        }
    }
}

/// Explains why an approval field was rejected.
#[derive(Clone, Copy, Debug, Eq, Error, PartialEq)]
pub enum InvalidApprovalField {
    /// The preview was empty or oversized.
    #[error("an approval preview must be 1 to {MAX_APPROVAL_PREVIEW_CHARS} characters")]
    Preview,
    /// The expiry was not after the creation time.
    #[error("an approval expiry must be after its creation time")]
    ExpiryNotAfterCreation,
    /// The lifetime exceeded [`MAX_APPROVAL_LIFETIME_SECONDS`].
    #[error("an approval may not live longer than {MAX_APPROVAL_LIFETIME_SECONDS} seconds")]
    LifetimeTooLong,
    /// The requested authentication strength was not a known value.
    #[error("unknown authentication strength")]
    UnknownStrength,
    /// The decision channel was not a known value.
    #[error("unknown approval channel")]
    UnknownChannel,
    /// The actor and approver were the same identity.
    #[error("an approver must not be the actor that requested the action")]
    SelfApproval,
    /// The decision used weaker authentication than the request requires.
    #[error("a decision needs {required} authentication but was supplied {supplied}")]
    InsufficientAuthentication {
        /// The strength the request requires.
        required: AuthenticationStrength,
        /// The strength the decision supplied.
        supplied: AuthenticationStrength,
    },
    /// The presented nonce did not match.
    #[error("the presented decision nonce does not match")]
    NonceMismatch,
    /// The request was loaded from storage, so its nonce is not available to compare.
    ///
    /// A store holds only the nonce's **digest**, so a decoded request cannot verify a presented
    /// nonce and must not pretend to. A caller in this position verifies the nonce against the stored
    /// digest and then calls [`ApprovalRequest::apply_verified_decision`]. This variant is what makes
    /// that requirement enforced rather than documented: without it, the placeholder nonce a decoded
    /// request holds would be a value somebody could present.
    #[error("this approval was loaded from storage; verify the nonce against the stored digest")]
    NonceUnavailable,
    /// A decision was already recorded.
    #[error("this approval has already been decided as {existing}")]
    AlreadyDecided {
        /// The state the approval is already in.
        existing: ApprovalState,
    },
    /// The approval had expired.
    #[error("this approval expired at {expired_at}")]
    Expired {
        /// When it expired.
        expired_at: UtcTimestamp,
    },
}

/// Where an approval is.
///
/// `Expired` is a state rather than a decision, because an approval that lapsed was never decided —
/// recording the lapse as a `Deny` would attribute a decision to a person who made none, and
/// `docs/architecture/runtime-and-models.md` distinguishes the documented `cancelled/expired` edge
/// from a cancellation.
#[derive(Clone, Copy, Debug, Deserialize, Eq, Hash, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum ApprovalState {
    /// Waiting for a decision.
    Pending,
    /// Approved, and within its lifetime.
    Approved,
    /// Denied by a person.
    Denied,
    /// Cancelled rather than decided.
    Cancelled,
    /// The lifetime elapsed without a decision.
    Expired,
}

impl ApprovalState {
    /// Returns the stable wire and storage name.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Pending => "pending",
            Self::Approved => "approved",
            Self::Denied => "denied",
            Self::Cancelled => "cancelled",
            Self::Expired => "expired",
        }
    }

    /// Returns whether the approval can still be decided.
    ///
    /// `Approved` is deliberately **not** decidable: an approval is a decision record, so allowing a
    /// second decision would make "the approval" ambiguous and would let a denial be overwritten by a
    /// later approval.
    #[must_use]
    pub const fn is_decidable(self) -> bool {
        matches!(self, Self::Pending)
    }

    /// Returns whether the approval authorized the action.
    ///
    /// Only `Approved`. Every other state — including `Expired` and `Cancelled`, which are not
    /// refusals — must be treated as "not authorized", so a caller checking this cannot mistake a
    /// lapse for permission.
    #[must_use]
    pub const fn authorizes(self) -> bool {
        matches!(self, Self::Approved)
    }

    /// Returns every state.
    #[must_use]
    pub const fn all() -> [Self; 5] {
        [
            Self::Pending,
            Self::Approved,
            Self::Denied,
            Self::Cancelled,
            Self::Expired,
        ]
    }
}

impl fmt::Display for ApprovalState {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.as_str())
    }
}

impl FromStr for ApprovalState {
    type Err = InvalidApprovalField;

    fn from_str(value: &str) -> Result<Self, Self::Err> {
        match value {
            "pending" => Ok(Self::Pending),
            "approved" => Ok(Self::Approved),
            "denied" => Ok(Self::Denied),
            "cancelled" => Ok(Self::Cancelled),
            "expired" => Ok(Self::Expired),
            _ => Err(InvalidApprovalField::UnknownChannel),
        }
    }
}

/// One decision to record against an approval.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ApprovalDecision {
    outcome: ApprovalDecisionOutcome,
    channel: ApprovalChannel,
    strength: AuthenticationStrength,
    decided_at: UtcTimestamp,
}

/// Which way a decision went.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum ApprovalDecisionOutcome {
    /// The action may proceed, within the lifetime.
    Approve,
    /// The action must not proceed.
    Deny,
    /// The request was withdrawn.
    Cancel,
}

impl ApprovalDecisionOutcome {
    /// Returns the state a decision produces.
    #[must_use]
    pub const fn state(self) -> ApprovalState {
        match self {
            Self::Approve => ApprovalState::Approved,
            Self::Deny => ApprovalState::Denied,
            Self::Cancel => ApprovalState::Cancelled,
        }
    }

    /// Returns the stable storage name.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Approve => "approve",
            Self::Deny => "deny",
            Self::Cancel => "cancel",
        }
    }
}

impl ApprovalDecision {
    /// Declares a decision.
    #[must_use]
    pub const fn new(
        outcome: ApprovalDecisionOutcome,
        channel: ApprovalChannel,
        strength: AuthenticationStrength,
        decided_at: UtcTimestamp,
    ) -> Self {
        Self {
            outcome,
            channel,
            strength,
            decided_at,
        }
    }

    /// Returns which way the decision went.
    #[must_use]
    pub const fn outcome(&self) -> ApprovalDecisionOutcome {
        self.outcome
    }

    /// Returns the channel that answered.
    #[must_use]
    pub const fn channel(&self) -> ApprovalChannel {
        self.channel
    }

    /// Returns the strength behind the decision.
    #[must_use]
    pub const fn strength(&self) -> AuthenticationStrength {
        self.strength
    }

    /// Returns when the decision was made.
    #[must_use]
    pub const fn decided_at(&self) -> UtcTimestamp {
        self.decided_at
    }
}

/// One durable approval request.
///
/// Immutable after construction except through [`Self::apply_decision`], which is the only door and
/// enforces the four rules in the module comment.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ApprovalRequest {
    id: ApprovalId,
    workspace_id: WorkspaceId,
    run_id: RunId,
    actor_id: String,
    tool: String,
    tool_version: String,
    intent: CanonicalIntentHash,
    preview: SafeMessage,
    risk_level: u8,
    required_strength: AuthenticationStrength,
    nonce: DecisionNonce,
    correlation_id: CorrelationId,
    created_at: UtcTimestamp,
    expires_at: UtcTimestamp,
    decision: Option<ApprovalDecision>,
    /// Whether this value holds the real nonce. `false` for a record rebuilt from storage, which
    /// holds only the digest — see [`InvalidApprovalField::NonceUnavailable`].
    nonce_usable: bool,
}

/// The declared fields of an approval request.
///
/// A struct rather than ten positional parameters, and without `Default`, so every field is stated
/// at the call site.
#[derive(Clone, Debug)]
pub struct ApprovalRequestParts {
    /// The approval identifier.
    pub id: ApprovalId,
    /// The workspace that owns the request.
    pub workspace_id: WorkspaceId,
    /// The run waiting on the decision.
    pub run_id: RunId,
    /// The actor that requested the action.
    pub actor_id: String,
    /// The tool being authorized.
    pub tool: String,
    /// The tool version the intent was built against.
    pub tool_version: String,
    /// The canonical hash of the exact intent.
    pub intent: CanonicalIntentHash,
    /// The human-readable preview.
    pub preview: String,
    /// The effect/risk level the decision was taken at.
    pub risk_level: u8,
    /// The strength a decision must be supplied with.
    pub required_strength: AuthenticationStrength,
    /// The one-time decision secret.
    pub nonce: DecisionNonce,
    /// The correlation identity shared with the originating request.
    pub correlation_id: CorrelationId,
    /// When the request was created.
    pub created_at: UtcTimestamp,
    /// When it lapses.
    pub expires_at: UtcTimestamp,
}

impl ApprovalRequest {
    /// Validates and records an approval request.
    ///
    /// # Errors
    ///
    /// Returns [`InvalidApprovalField::Preview`] for an empty or oversized preview,
    /// [`InvalidApprovalField::ExpiryNotAfterCreation`] when the expiry does not follow the creation
    /// time, or [`InvalidApprovalField::LifetimeTooLong`] when it exceeds
    /// [`MAX_APPROVAL_LIFETIME_SECONDS`].
    pub fn new(parts: ApprovalRequestParts) -> Result<Self, InvalidApprovalField> {
        let ApprovalRequestParts {
            id,
            workspace_id,
            run_id,
            actor_id,
            tool,
            tool_version,
            intent,
            preview,
            risk_level,
            required_strength,
            nonce,
            correlation_id,
            created_at,
            expires_at,
        } = parts;

        let preview = SafeMessage::new(preview).map_err(|_| InvalidApprovalField::Preview)?;
        if preview.as_str().chars().count() > MAX_APPROVAL_PREVIEW_CHARS {
            return Err(InvalidApprovalField::Preview);
        }

        // Compared as instants, not as text. See the module comment for why the stored form cannot be
        // compared lexicographically.
        let created_nanos = created_at.unix_nanos();
        let expiry_nanos = expires_at.unix_nanos();
        if expiry_nanos <= created_nanos {
            return Err(InvalidApprovalField::ExpiryNotAfterCreation);
        }
        let lifetime_seconds = (expiry_nanos - created_nanos) / 1_000_000_000;
        if lifetime_seconds > i128::from(MAX_APPROVAL_LIFETIME_SECONDS) {
            return Err(InvalidApprovalField::LifetimeTooLong);
        }

        Ok(Self {
            id,
            workspace_id,
            run_id,
            actor_id,
            tool,
            tool_version,
            intent,
            preview,
            risk_level,
            required_strength,
            nonce,
            correlation_id,
            created_at,
            expires_at,
            decision: None,
            nonce_usable: true,
        })
    }

    /// Rebuilds a request from stored fields, which the store has already validated.
    ///
    /// # Errors
    ///
    /// Returns the same failures as [`Self::new`] when a stored row disagrees with the invariants —
    /// so a hand-edited row cannot produce a request that in-memory construction would have refused.
    ///
    /// The resulting request **cannot verify a nonce** ([`InvalidApprovalField::NonceUnavailable`]),
    /// because only the nonce's digest is stored. A caller must verify against the stored digest and
    /// then call [`Self::apply_verified_decision`], which is the only honest sequence available.
    pub fn from_stored(
        parts: ApprovalRequestParts,
        decision: Option<ApprovalDecision>,
    ) -> Result<Self, InvalidApprovalField> {
        let request = Self::new(parts)?;
        Ok(Self {
            decision,
            nonce_usable: false,
            ..request
        })
    }

    /// Applies a decision, returning the decided request.
    ///
    /// # Errors
    ///
    /// - [`InvalidApprovalField::AlreadyDecided`] when a decision is already recorded, so a denial
    ///   cannot be overwritten by a later approval.
    /// - [`InvalidApprovalField::NonceMismatch`] when the presented nonce does not match, which is
    ///   the control against a forged decision.
    /// - [`InvalidApprovalField::InsufficientAuthentication`] when the decision used weaker
    ///   authentication than the request requires. An approval that was not proven as strongly as
    ///   the action requires is not an approval for that action.
    /// - [`InvalidApprovalField::Expired`] when the decision arrives after the expiry. Checked
    ///   against `decided_at` rather than a separate clock read, so the decision's own timestamp is
    ///   what is judged.
    /// - [`InvalidApprovalField::SelfApproval`] when the approver is the requesting actor.
    ///
    /// # Why `decided_at` is a parameter rather than read from a clock
    ///
    /// So the function stays pure and the expiry check is testable at a chosen instant. A function
    /// that read a clock would make "an expired approval cannot be approved" a test of timing rather
    /// than of logic.
    pub fn apply_decision(
        &self,
        approver_id: &str,
        presented_nonce: &str,
        decision: ApprovalDecision,
    ) -> Result<Self, InvalidApprovalField> {
        // A request loaded from storage holds a placeholder instead of the nonce, so comparing what
        // it holds would either always fail or, worse, accept the placeholder as the secret. Refusing
        // outright forces the caller onto the digest path.
        if !self.nonce_usable {
            return Err(InvalidApprovalField::NonceUnavailable);
        }
        if !self.nonce.matches(presented_nonce) {
            return Err(InvalidApprovalField::NonceMismatch);
        }
        self.apply_verified_decision(approver_id, decision)
    }

    /// Applies a decision whose nonce has **already been verified** against the stored digest.
    ///
    /// # Errors
    ///
    /// - [`InvalidApprovalField::AlreadyDecided`] when a decision is already recorded, so a denial
    ///   cannot be overwritten by a later approval.
    /// - [`InvalidApprovalField::InsufficientAuthentication`] when the decision used weaker
    ///   authentication than the request requires. An approval that was not proven as strongly as
    ///   the action requires is not an approval for that action.
    /// - [`InvalidApprovalField::Expired`] when the decision arrives after the expiry. Checked
    ///   against `decided_at` rather than a separate clock read, so the decision's own timestamp is
    ///   what is judged.
    /// - [`InvalidApprovalField::SelfApproval`] when the approver is the requesting actor.
    ///
    /// # Why this is public and `apply_decision` delegates to it
    ///
    /// The nonce can only be verified by whoever holds its digest, which is the store rather than the
    /// domain. Splitting the function means every other rule still has exactly one home, and the
    /// nonce check has one home too — in the store, where the digest is. The alternative was to
    /// re-implement the strength floor and the expiry in SQL, which would have been two copies of a
    /// security rule.
    ///
    /// # Why `decided_at` is a parameter rather than read from a clock
    ///
    /// So the function stays pure and the expiry check is testable at a chosen instant. A function
    /// that read a clock would make "an expired approval cannot be approved" a test of timing rather
    /// than of logic.
    pub fn apply_verified_decision(
        &self,
        approver_id: &str,
        decision: ApprovalDecision,
    ) -> Result<Self, InvalidApprovalField> {
        if let Some(existing) = self.decision.as_ref() {
            return Err(InvalidApprovalField::AlreadyDecided {
                existing: existing.outcome().state(),
            });
        }
        // The actor that asked for the action must not answer for it. A model requesting a call and
        // then approving it is the confused-deputy case `security.md` names, and for a local
        // single-owner profile the actor is the user, so an equal identifier is either a bug or a
        // forged request.
        if approver_id == self.actor_id {
            return Err(InvalidApprovalField::SelfApproval);
        }
        // An approval is not a permanent bearer token: a decision taken after the expiry does not
        // authorize anything, whatever it says.
        if decision.decided_at().unix_nanos() >= self.expires_at.unix_nanos() {
            return Err(InvalidApprovalField::Expired {
                expired_at: self.expires_at,
            });
        }
        if decision.strength() < self.required_strength {
            return Err(InvalidApprovalField::InsufficientAuthentication {
                required: self.required_strength,
                supplied: decision.strength(),
            });
        }
        Ok(Self {
            decision: Some(decision),
            ..self.clone()
        })
    }

    /// Returns the state at an instant.
    ///
    /// Derived rather than stored for the time-dependent part: a stored `expired` flag would be
    /// wrong the moment it was written, and a sweep job that updated it would be a requirement for
    /// correctness rather than a tidy-up.
    #[must_use]
    pub fn state_at(&self, now: UtcTimestamp) -> ApprovalState {
        match self.decision.as_ref() {
            // A decided approval reports its decision until it lapses.
            Some(decision) => {
                if decision.outcome() == ApprovalDecisionOutcome::Approve
                    && now.unix_nanos() >= self.expires_at.unix_nanos()
                {
                    ApprovalState::Expired
                } else {
                    decision.outcome().state()
                }
            }
            None => {
                if now.unix_nanos() >= self.expires_at.unix_nanos() {
                    ApprovalState::Expired
                } else {
                    ApprovalState::Pending
                }
            }
        }
    }

    /// Returns the state at the instant the request was created, which is the stored state.
    ///
    /// Used by the store, which must never read a clock: a row's stored state is a function of the
    /// row and its decision, and it becomes `Expired` on read once the lifetime elapses.
    #[must_use]
    pub fn stored_state(&self) -> ApprovalState {
        match self.decision.as_ref() {
            Some(decision) => decision.outcome().state(),
            None => ApprovalState::Pending,
        }
    }

    /// Returns whether the approval authorizes the action at an instant.
    #[must_use]
    pub fn authorizes_at(&self, now: UtcTimestamp) -> bool {
        self.state_at(now).authorizes()
    }

    /// Returns the approval identifier.
    #[must_use]
    pub const fn id(&self) -> ApprovalId {
        self.id
    }

    /// Returns the owning workspace.
    #[must_use]
    pub const fn workspace_id(&self) -> WorkspaceId {
        self.workspace_id
    }

    /// Returns the run waiting on the decision.
    #[must_use]
    pub const fn run_id(&self) -> RunId {
        self.run_id
    }

    /// Returns the actor that requested the action.
    #[must_use]
    pub fn actor_id(&self) -> &str {
        &self.actor_id
    }

    /// Returns the tool being authorized.
    #[must_use]
    pub fn tool(&self) -> &str {
        &self.tool
    }

    /// Returns the tool version the intent was built against.
    #[must_use]
    pub fn tool_version(&self) -> &str {
        &self.tool_version
    }

    /// Returns the canonical intent the decision binds to.
    #[must_use]
    pub const fn intent(&self) -> CanonicalIntentHash {
        self.intent
    }

    /// Returns the human-readable preview.
    #[must_use]
    pub const fn preview(&self) -> &SafeMessage {
        &self.preview
    }

    /// Returns the effect/risk level the decision was taken at.
    #[must_use]
    pub const fn risk_level(&self) -> u8 {
        self.risk_level
    }

    /// Returns the strength a decision must be supplied with.
    #[must_use]
    pub const fn required_strength(&self) -> AuthenticationStrength {
        self.required_strength
    }

    /// Returns the correlation identity.
    #[must_use]
    pub const fn correlation_id(&self) -> CorrelationId {
        self.correlation_id
    }

    /// Returns when the request was created.
    #[must_use]
    pub const fn created_at(&self) -> UtcTimestamp {
        self.created_at
    }

    /// Returns when the request lapses.
    #[must_use]
    pub const fn expires_at(&self) -> UtcTimestamp {
        self.expires_at
    }

    /// Returns the recorded decision, when one exists.
    #[must_use]
    pub const fn decision(&self) -> Option<&ApprovalDecision> {
        self.decision.as_ref()
    }

    /// Returns the encoded nonce, for storage.
    #[must_use]
    pub fn nonce_for_storage(&self) -> &str {
        self.nonce.expose()
    }

    /// Returns when the request lapses, computed from a clock, for a caller that has one.
    ///
    /// Provided so a caller does not hand-roll `created_at + MAX_APPROVAL_LIFETIME_SECONDS` and
    /// produce a value this type would refuse.
    #[must_use]
    pub fn default_expiry(clock: &impl Clock) -> UtcTimestamp {
        let now = UtcTimestamp::now(clock);
        UtcTimestamp::from_unix_nanos(
            now.unix_nanos() + i128::from(MAX_APPROVAL_LIFETIME_SECONDS) * 1_000_000_000,
        )
        .unwrap_or(now)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    struct At(i128);

    impl Clock for At {
        fn now(&self) -> UtcTimestamp {
            UtcTimestamp::from_unix_nanos(self.0).unwrap_or_else(|error| panic!("{error}"))
        }
    }

    fn base() -> i128 {
        1_789_977_600_000_000_000
    }

    fn at(offset_seconds: i128) -> UtcTimestamp {
        At(base() + offset_seconds * 1_000_000_000).now()
    }

    fn id() -> ApprovalId {
        ApprovalId::new()
    }

    fn workspace() -> WorkspaceId {
        WorkspaceId::new()
    }

    fn run() -> RunId {
        RunId::new()
    }

    fn correlation() -> CorrelationId {
        CorrelationId::new()
    }

    /// A pending request for a risk-3 destructive action needing presence.
    fn request() -> ApprovalRequest {
        let intent =
            CanonicalIntentHash::compute("jarvis.mail.purge", "1.0.0", &json!({"all": true}))
                .unwrap_or_else(|error| panic!("intent: {error}"));
        ApprovalRequest::new(ApprovalRequestParts {
            id: id(),
            workspace_id: workspace(),
            run_id: run(),
            actor_id: "actor-1".to_owned(),
            tool: "jarvis.mail.purge".to_owned(),
            tool_version: "1.0.0".to_owned(),
            intent,
            preview: "Delete every message in the mailbox.".to_owned(),
            risk_level: 3,
            required_strength: AuthenticationStrength::Present,
            nonce: DecisionNonce::generate().unwrap_or_else(|error| panic!("nonce: {error}")),
            correlation_id: correlation(),
            created_at: at(0),
            expires_at: at(600),
        })
        .unwrap_or_else(|error| panic!("request: {error}"))
    }

    fn decision(
        outcome: ApprovalDecisionOutcome,
        strength: AuthenticationStrength,
        offset: i128,
    ) -> ApprovalDecision {
        ApprovalDecision::new(outcome, ApprovalChannel::Desktop, strength, at(offset))
    }

    /// A canonical hash is deterministic and independent of key order.
    ///
    /// The property the whole binding rests on: the same intent must hash identically however the
    /// argument object was built, or an approval would fail to match the action it approved.
    #[test]
    fn a_canonical_hash_is_deterministic_and_key_order_independent() {
        let first = CanonicalIntentHash::compute(
            "jarvis.mail.send",
            "1.0.0",
            &json!({"to": "a@example.invalid", "subject": "hi", "priority": 1}),
        )
        .unwrap_or_else(|error| panic!("{error}"));
        let reordered = CanonicalIntentHash::compute(
            "jarvis.mail.send",
            "1.0.0",
            &json!({"priority": 1, "subject": "hi", "to": "a@example.invalid"}),
        )
        .unwrap_or_else(|error| panic!("{error}"));
        assert_eq!(first, reordered, "key order must not change the intent");
        assert_eq!(first.to_hex().len(), 64);
        assert_eq!(first.to_hex(), reordered.to_hex());
    }

    /// **Any change to the intent changes the hash, which is what invalidates an approval.**
    ///
    /// `security.md`: "Editing the action invalidates the approval." Asserted per change so the
    /// claim is not an assumption about SHA-256 but a property of how the parts are combined.
    #[test]
    fn any_change_to_the_intent_changes_the_hash() {
        let baseline = CanonicalIntentHash::compute(
            "jarvis.mail.send",
            "1.0.0",
            &json!({"to": "a@example.invalid"}),
        )
        .unwrap_or_else(|error| panic!("{error}"));

        let changed_arguments = CanonicalIntentHash::compute(
            "jarvis.mail.send",
            "1.0.0",
            &json!({"to": "b@example.invalid"}),
        )
        .unwrap_or_else(|error| panic!("{error}"));
        assert_ne!(baseline, changed_arguments, "a different target");

        let changed_version = CanonicalIntentHash::compute(
            "jarvis.mail.send",
            "1.0.1",
            &json!({"to": "a@example.invalid"}),
        )
        .unwrap_or_else(|error| panic!("{error}"));
        assert_ne!(baseline, changed_version, "a different tool version");

        let changed_tool = CanonicalIntentHash::compute(
            "jarvis.mail.forward",
            "1.0.0",
            &json!({"to": "a@example.invalid"}),
        )
        .unwrap_or_else(|error| panic!("{error}"));
        assert_ne!(baseline, changed_tool, "a different tool");

        // Even an extra field that changes nothing about the operation invalidates it, because the
        // decision bound to the arguments as they were.
        let extra_field = CanonicalIntentHash::compute(
            "jarvis.mail.send",
            "1.0.0",
            &json!({"to": "a@example.invalid", "cc": []}),
        )
        .unwrap_or_else(|error| panic!("{error}"));
        assert_ne!(baseline, extra_field, "an added field");
    }

    /// **The separator matters: parts must not be able to bleed into each other.**
    ///
    /// Without a separator between the tool and the version, `("a", "bc", args)` and `("ab", "c",
    /// args)` would produce the same digest — so one approval would authorize the other tool.
    #[test]
    fn the_parts_cannot_bleed_into_each_other() {
        let first = CanonicalIntentHash::compute("a", "bc", &json!({}))
            .unwrap_or_else(|error| panic!("{error}"));
        let second = CanonicalIntentHash::compute("ab", "c", &json!({}))
            .unwrap_or_else(|error| panic!("{error}"));
        assert_ne!(first, second, "tool and version must not be ambiguous");
    }

    /// Non-object arguments are refused, because a validated tool call always has an object.
    #[test]
    fn non_object_arguments_are_refused() {
        assert_eq!(
            CanonicalIntentHash::compute("jarvis.mail.send", "1.0.0", &json!([1, 2, 3])),
            Err(IntentError::ArgumentsNotAnObject)
        );
        assert_eq!(
            CanonicalIntentHash::compute("jarvis.mail.send", "1.0.0", &json!("text")),
            Err(IntentError::ArgumentsNotAnObject)
        );
    }

    /// An oversized intent is refused before it is hashed.
    #[test]
    fn an_oversized_intent_is_refused() {
        let huge = json!({ "body": "x".repeat(MAX_CANONICAL_INTENT_CHARS) });
        assert_eq!(
            CanonicalIntentHash::compute("jarvis.mail.send", "1.0.0", &huge),
            Err(IntentError::TooLong)
        );
    }

    /// A hash round-trips through its stored text form, and a malformed one is refused.
    #[test]
    fn a_hash_round_trips_and_malformed_text_is_refused() {
        let hash = CanonicalIntentHash::compute("jarvis.mail.send", "1.0.0", &json!({}))
            .unwrap_or_else(|error| panic!("{error}"));
        let encoded = serde_json::to_string(&hash).unwrap_or_else(|error| panic!("{error}"));
        let decoded: CanonicalIntentHash =
            serde_json::from_str(&encoded).unwrap_or_else(|error| panic!("{error}"));
        assert_eq!(decoded, hash);

        for malformed in ["", "abc", &"z".repeat(64), &"a".repeat(63), &"a".repeat(65)] {
            assert!(
                malformed.parse::<CanonicalIntentHash>().is_err(),
                "{malformed:?} must not parse as a digest"
            );
        }
        // Uppercase is accepted on parse and normalized, so a stored digest is not case-dependent.
        let upper = hash.to_hex().to_uppercase();
        assert_eq!(
            upper
                .parse::<CanonicalIntentHash>()
                .unwrap_or_else(|error| panic!("{error}"))
                .to_hex(),
            hash.to_hex()
        );
    }

    /// **A nonce is generated, is a fixed length, and is redacted from `Debug`.**
    #[test]
    fn a_nonce_is_generated_and_redacted() {
        let nonce = DecisionNonce::generate().unwrap_or_else(|error| panic!("{error}"));
        assert_eq!(nonce.expose().len(), CREDENTIAL_CHARS);
        assert!(nonce.expose().bytes().all(|byte| byte.is_ascii_hexdigit()));

        let rendered = format!("{nonce:?}");
        assert!(
            !rendered.contains(nonce.expose()),
            "a nonce must not appear in a debug rendering: {rendered}"
        );
        assert!(rendered.contains("REDACTED"));
        assert!(!format!("{nonce}").contains(nonce.expose()));

        // Two nonces differ, so generation is not a constant.
        let other = DecisionNonce::generate().unwrap_or_else(|error| panic!("{error}"));
        assert_ne!(nonce, other);
    }

    /// A nonce matches what it was generated as, and nothing else.
    #[test]
    fn a_nonce_matches_only_itself() {
        let nonce = DecisionNonce::generate().unwrap_or_else(|error| panic!("{error}"));
        assert!(nonce.matches(nonce.expose()));
        assert!(!nonce.matches(&"0".repeat(CREDENTIAL_CHARS)));
        assert!(!nonce.matches(""));
        assert!(!nonce.matches("short"));
    }

    /// A malformed presented nonce is refused rather than compared.
    #[test]
    fn a_malformed_nonce_is_refused() {
        assert_eq!(DecisionNonce::parse("abc"), Err(NonceError::Length));
        assert_eq!(
            DecisionNonce::parse(&"z".repeat(CREDENTIAL_CHARS)),
            Err(NonceError::NotHexadecimal)
        );
        // Valid hexadecimal of the right length parses, and case is normalized.
        let parsed = DecisionNonce::parse(&"AB".repeat(CREDENTIAL_CHARS / 2))
            .unwrap_or_else(|error| panic!("{error}"));
        assert_eq!(parsed.expose(), "ab".repeat(CREDENTIAL_CHARS / 2));
    }

    /// An approval is pending before its expiry and expired after it.
    #[test]
    fn an_undecided_approval_expires_on_read() {
        let request = request();
        assert_eq!(request.state_at(at(0)), ApprovalState::Pending);
        assert_eq!(request.state_at(at(599)), ApprovalState::Pending);
        assert_eq!(request.state_at(at(600)), ApprovalState::Expired);
        assert_eq!(request.state_at(at(10_000)), ApprovalState::Expired);
        assert!(!request.authorizes_at(at(599)));
        assert!(!request.authorizes_at(at(600)));
        // The stored state does not move, because a row cannot read a clock.
        assert_eq!(request.stored_state(), ApprovalState::Pending);
    }

    /// **A decision with the right nonce and strength is recorded, and authorizes the action.**
    #[test]
    fn a_valid_decision_is_recorded_and_authorizes() {
        let request = request();
        let decided = request
            .apply_decision(
                "user-1",
                request.nonce_for_storage(),
                decision(
                    ApprovalDecisionOutcome::Approve,
                    AuthenticationStrength::Present,
                    10,
                ),
            )
            .unwrap_or_else(|error| panic!("a valid decision: {error}"));

        assert_eq!(decided.stored_state(), ApprovalState::Approved);
        assert!(decided.authorizes_at(at(20)));
        assert_eq!(decided.state_at(at(20)), ApprovalState::Approved);
        // It still lapses: an approval is not a permanent bearer token.
        assert_eq!(decided.state_at(at(600)), ApprovalState::Expired);
        assert!(!decided.authorizes_at(at(600)));
        // The undecided original is unchanged, so applying a decision is not a mutation.
        assert_eq!(request.stored_state(), ApprovalState::Pending);
    }

    /// **A decision with the wrong nonce is refused.**
    ///
    /// The forgery case: a caller that can guess or read a nonce could decide an approval it was not
    /// asked for.
    #[test]
    fn a_decision_with_the_wrong_nonce_is_refused() {
        let request = request();
        let forged = "0".repeat(CREDENTIAL_CHARS);
        assert_eq!(
            request.apply_decision(
                "user-1",
                &forged,
                decision(
                    ApprovalDecisionOutcome::Approve,
                    AuthenticationStrength::Present,
                    10
                )
            ),
            Err(InvalidApprovalField::NonceMismatch)
        );
        assert_eq!(request.stored_state(), ApprovalState::Pending);
    }

    /// **A decision weaker than the request requires is refused.**
    ///
    /// A voice confirmation is `ChannelEvidence`, which is below the `Present` a risk-3 action
    /// requires, so `security.md`'s "voice confirmation alone is insufficient" becomes a refusal
    /// rather than a convention.
    #[test]
    fn a_decision_weaker_than_required_is_refused() {
        let request = request();
        for supplied in [
            AuthenticationStrength::Absent,
            AuthenticationStrength::ChannelEvidence,
            AuthenticationStrength::Credential,
        ] {
            assert_eq!(
                request.apply_decision(
                    "user-1",
                    request.nonce_for_storage(),
                    decision(ApprovalDecisionOutcome::Approve, supplied, 10)
                ),
                Err(InvalidApprovalField::InsufficientAuthentication {
                    required: AuthenticationStrength::Present,
                    supplied
                }),
                "{supplied} must not decide a presence-required approval"
            );
        }
        // The required strength itself is sufficient, so the check is a floor and not strict.
        assert!(
            request
                .apply_decision(
                    "user-1",
                    request.nonce_for_storage(),
                    decision(
                        ApprovalDecisionOutcome::Approve,
                        AuthenticationStrength::Present,
                        10
                    )
                )
                .is_ok(),
            "the required strength itself must be sufficient"
        );
    }

    /// **A decision taken after the expiry is refused.**
    #[test]
    fn a_decision_after_the_expiry_is_refused() {
        let request = request();
        for offset in [600, 601, 10_000] {
            assert_eq!(
                request.apply_decision(
                    "user-1",
                    request.nonce_for_storage(),
                    decision(
                        ApprovalDecisionOutcome::Approve,
                        AuthenticationStrength::Present,
                        offset
                    )
                ),
                Err(InvalidApprovalField::Expired {
                    expired_at: at(600)
                }),
                "a decision at {offset} is after the expiry"
            );
        }
        // One nanosecond before is still inside the lifetime, so the boundary is the expiry itself.
        let just_in_time = request
            .apply_decision(
                "user-1",
                request.nonce_for_storage(),
                decision(
                    ApprovalDecisionOutcome::Approve,
                    AuthenticationStrength::Present,
                    599,
                ),
            )
            .unwrap_or_else(|error| panic!("{error}"));
        assert!(just_in_time.authorizes_at(at(599)));
    }

    /// **A second decision is refused, so a denial cannot be overwritten by a later approval.**
    ///
    /// The replay case: without this, an approver who denied the action could have the record
    /// replaced.
    #[test]
    fn a_second_decision_is_refused() {
        let request = request();
        let denied = request
            .apply_decision(
                "user-1",
                request.nonce_for_storage(),
                decision(
                    ApprovalDecisionOutcome::Deny,
                    AuthenticationStrength::Present,
                    10,
                ),
            )
            .unwrap_or_else(|error| panic!("{error}"));
        assert_eq!(denied.stored_state(), ApprovalState::Denied);

        assert_eq!(
            denied.apply_decision(
                "user-2",
                request.nonce_for_storage(),
                decision(
                    ApprovalDecisionOutcome::Approve,
                    AuthenticationStrength::Present,
                    20
                )
            ),
            Err(InvalidApprovalField::AlreadyDecided {
                existing: ApprovalState::Denied
            }),
            "a denial must not be replaceable by an approval"
        );
        assert!(!denied.authorizes_at(at(20)));
    }

    /// **The requesting actor cannot approve its own request.**
    ///
    /// `security.md` names "model self-approval / confused deputy" as the threat this control exists
    /// for. For a local single-owner profile the actor is the user, so an equal identifier is either
    /// a bug or a forged request, and refusing is the fail-closed choice.
    #[test]
    fn the_requesting_actor_cannot_approve_its_own_request() {
        let request = request();
        assert_eq!(
            request.apply_decision(
                request.actor_id(),
                request.nonce_for_storage(),
                decision(
                    ApprovalDecisionOutcome::Approve,
                    AuthenticationStrength::Present,
                    10
                )
            ),
            Err(InvalidApprovalField::SelfApproval)
        );
        assert_eq!(request.stored_state(), ApprovalState::Pending);
    }

    /// An expiry that does not follow the creation time is refused.
    #[test]
    fn an_unusable_expiry_is_refused() {
        let mut parts = ApprovalRequestParts {
            id: id(),
            workspace_id: workspace(),
            run_id: run(),
            actor_id: "actor-1".to_owned(),
            tool: "jarvis.mail.purge".to_owned(),
            tool_version: "1.0.0".to_owned(),
            intent: CanonicalIntentHash::compute("jarvis.mail.purge", "1.0.0", &json!({}))
                .unwrap_or_else(|error| panic!("{error}")),
            preview: "Delete everything.".to_owned(),
            risk_level: 3,
            required_strength: AuthenticationStrength::Present,
            nonce: DecisionNonce::generate().unwrap_or_else(|error| panic!("{error}")),
            correlation_id: correlation(),
            created_at: at(0),
            expires_at: at(0),
        };
        assert_eq!(
            ApprovalRequest::new(parts.clone()),
            Err(InvalidApprovalField::ExpiryNotAfterCreation)
        );

        parts.expires_at = at(-1);
        assert_eq!(
            ApprovalRequest::new(parts.clone()),
            Err(InvalidApprovalField::ExpiryNotAfterCreation)
        );

        parts.expires_at = at(i128::from(MAX_APPROVAL_LIFETIME_SECONDS) + 1);
        assert_eq!(
            ApprovalRequest::new(parts.clone()),
            Err(InvalidApprovalField::LifetimeTooLong)
        );

        // The maximum itself is accepted, so the bound is a bound and not an off-by-one.
        parts.expires_at = at(i128::from(MAX_APPROVAL_LIFETIME_SECONDS));
        assert!(ApprovalRequest::new(parts).is_ok());
    }

    /// An empty or oversized preview is refused.
    #[test]
    fn an_unusable_preview_is_refused() {
        let mut parts = ApprovalRequestParts {
            id: id(),
            workspace_id: workspace(),
            run_id: run(),
            actor_id: "actor-1".to_owned(),
            tool: "jarvis.mail.purge".to_owned(),
            tool_version: "1.0.0".to_owned(),
            intent: CanonicalIntentHash::compute("jarvis.mail.purge", "1.0.0", &json!({}))
                .unwrap_or_else(|error| panic!("{error}")),
            preview: String::new(),
            risk_level: 3,
            required_strength: AuthenticationStrength::Present,
            nonce: DecisionNonce::generate().unwrap_or_else(|error| panic!("{error}")),
            correlation_id: correlation(),
            created_at: at(0),
            expires_at: at(600),
        };
        assert_eq!(
            ApprovalRequest::new(parts.clone()),
            Err(InvalidApprovalField::Preview)
        );

        parts.preview = "x".repeat(MAX_APPROVAL_PREVIEW_CHARS + 1);
        assert_eq!(
            ApprovalRequest::new(parts.clone()),
            Err(InvalidApprovalField::Preview)
        );

        parts.preview = "ok".to_owned();
        assert!(ApprovalRequest::new(parts).is_ok());
    }

    /// **A cancel is a decision, and it grants nothing.**
    #[test]
    fn a_cancel_grants_nothing() {
        let request = request();
        let cancelled = request
            .apply_decision(
                "user-1",
                request.nonce_for_storage(),
                decision(
                    ApprovalDecisionOutcome::Cancel,
                    AuthenticationStrength::Present,
                    5,
                ),
            )
            .unwrap_or_else(|error| panic!("{error}"));
        assert_eq!(cancelled.stored_state(), ApprovalState::Cancelled);
        assert!(!cancelled.authorizes_at(at(10)));
    }

    /// The stored state is a function of the row, so a decided approval reports its decision.
    #[test]
    fn the_stored_state_follows_the_decision() {
        let request = request();
        for outcome in [
            ApprovalDecisionOutcome::Approve,
            ApprovalDecisionOutcome::Deny,
            ApprovalDecisionOutcome::Cancel,
        ] {
            let decided = request
                .apply_decision(
                    "user-1",
                    request.nonce_for_storage(),
                    decision(outcome, AuthenticationStrength::Present, 5),
                )
                .unwrap_or_else(|error| panic!("{outcome:?}: {error}"));
            assert_eq!(decided.stored_state(), outcome.state());
        }
    }

    /// Every state's name round-trips, and only `Pending` is decidable.
    #[test]
    fn states_round_trip_and_only_pending_is_decidable() {
        for state in ApprovalState::all() {
            assert_eq!(state.as_str().parse::<ApprovalState>(), Ok(state));
            let encoded = serde_json::to_string(&state).unwrap_or_else(|error| panic!("{error}"));
            assert_eq!(encoded, format!("\"{}\"", state.as_str()));
            assert_eq!(state.is_decidable(), state == ApprovalState::Pending);
            assert_eq!(state.authorizes(), state == ApprovalState::Approved);
        }
    }

    /// Every strength and channel name round-trips, and the ordering is documented.
    #[test]
    fn strengths_and_channels_round_trip() {
        for strength in AuthenticationStrength::all() {
            assert_eq!(
                strength.as_str().parse::<AuthenticationStrength>(),
                Ok(strength)
            );
            let encoded =
                serde_json::to_string(&strength).unwrap_or_else(|error| panic!("{error}"));
            assert_eq!(encoded, format!("\"{}\"", strength.as_str()));
        }
        assert!(AuthenticationStrength::Absent < AuthenticationStrength::Present);
        assert_eq!(AuthenticationStrength::Absent.level(), 0);
        assert_eq!(AuthenticationStrength::Present.level(), 3);

        for channel in ApprovalChannel::all() {
            assert_eq!(channel.as_str().parse::<ApprovalChannel>(), Ok(channel));
        }
        assert!("smoke_signal".parse::<ApprovalChannel>().is_err());
    }

    /// The default expiry is inside the bound the type accepts, from any clock.
    #[test]
    fn the_default_expiry_is_within_the_bound() {
        let clock = At(base());
        let expiry = ApprovalRequest::default_expiry(&clock);
        let created = at(0);
        let lifetime = (expiry.unix_nanos() - created.unix_nanos()) / 1_000_000_000;
        assert_eq!(lifetime, i128::from(MAX_APPROVAL_LIFETIME_SECONDS));
        assert!(expiry > created);
    }
}
